version: "3.8"

services:
  web:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:5555

  api:
    build: 
      context: ./backend
    ports:
      - "5555:5555"
    environment:
      DB_URL: "mongodb+srv://pasan:pasan123@vegitableshop1.36odzch.mongodb.net/?retryWrites=true&w=majority&appName=vegitableshop1"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
